# backend/Dockerfile.dev
FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy dependency files
COPY package*.json tsconfig.json ./

# Install ALL dependencies (including dev)
RUN npm install

# Copy the rest of the source code
COPY . .

# Expose backend port
EXPOSE 4000

# Run app with nodemon for auto reload
CMD ["npm", "run", "dev"]
