export const ITINERARY_TYPES = [
  { label: 'itinerary.type.city', value: 'city' },
  { label: 'itinerary.type.beach', value: 'beach' },
  { label: 'itinerary.type.road', value: 'road' },
  { label: 'itinerary.type.business', value: 'business' },
  { label: 'itinerary.type.education', value: 'education' },
  { label: 'itinerary.type.couple', value: 'couple' },
  { label: 'itinerary.type.family', value: 'family' },
  { label: 'itinerary.type.weekend', value: 'weekend' },
  { label: 'itinerary.type.vacation', value: 'vacation' },
  { label: 'itinerary.type.adventure', value: 'adventure' },
  { label: 'itinerary.type.backpacking', value: 'backpacking' },
  { label: 'itinerary.type.event', value: 'event' },
  { label: 'itinerary.type.pilgrimage', value: 'pilgrimage' },
  { label: 'itinerary.type.cruise', value: 'cruise' },
  { label: 'itinerary.type.staycation', value: 'staycation' },
  { label: 'itinerary.type.other', value: 'other' },
];