export const ITINERARY_TYPES = [
  { label: 'City Trip', value: 'city' },
  { label: 'Beach Trip', value: 'beach' },
  { label: 'Road Trip', value: 'road' },
  { label: 'Business Trip', value: 'business' },
  { label: 'Educational Trip', value: 'education' },
  { label: 'Couple Trip', value: 'couple' },
  { label: 'Family Trip', value: 'family' },
  { label: 'Weekend Trip', value: 'weekend' },
  { label: 'Vacation', value: 'vacation' },
  { label: 'Adventure', value: 'adventure' },
  { label: 'Backpacking', value: 'backpacking' },
  { label: 'Event', value: 'event' },
  { label: 'Pilgrimage', value: 'pilgrimage' },
  { label: 'Cruise', value: 'cruise' },
  { label: 'Staycation', value: 'staycation' },
  { label: 'Other', value: 'other' },
];